In [2]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

In [3]:
torch.manual_seed(1)

In [4]:
x_train = [[1, 2, 1, 1],
           [2, 1, 3, 2],
           [3, 1, 3, 4],
           [4, 1, 5, 5],
           [1, 7, 5, 5],
           [1, 2, 5, 6],
           [1, 6, 6, 6],
           [1, 7, 7, 7]]
y_train = [2, 2, 2, 1, 1, 1, 0, 0]
x_train = torch.FloatTensor(x_train)
y_train = torch.LongTensor(y_train)

In [5]:
print(x_train.shape)
print(y_train.shape)

torch.Size([8, 4])
torch.Size([8])


In [8]:
y_one_hot = torch.zeros(8,3)

print(y_one_hot)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


In [10]:
y_one_hot.scatter_(1, y_train.unsqueeze(1), 1)
print(y_one_hot)

tensor([[0., 0., 1.],
        [0., 0., 1.],
        [0., 0., 1.],
        [0., 1., 0.],
        [0., 1., 0.],
        [0., 1., 0.],
        [1., 0., 0.],
        [1., 0., 0.]])


In [11]:
print(y_train.unsqueeze(1))

tensor([[2],
        [2],
        [2],
        [1],
        [1],
        [1],
        [0],
        [0]])


In [12]:
w = torch.zeros((4,3), requires_grad=True)
b = torch.zeros((8,3), requires_grad=True)

In [13]:
optimizer = optim.SGD([w,b],lr=0.1)

In [15]:
nb_epochs = 1000
for epoch in range(nb_epochs+1):
    hypo = x_train.matmul(w)+b
    cost = F.cross_entropy(hypo, y_train)
    
    optimizer.zero_grad()
    cost.backward()
    optimizer.step()
    
    if epoch % 10 ==0:
        print('epoch {:4d}/{} cost {:4f}'.format(epoch, nb_epochs, cost.item()))
        

epoch    0/1000 cost 0.036812
epoch   10/1000 cost 0.036439
epoch   20/1000 cost 0.036073
epoch   30/1000 cost 0.035715
epoch   40/1000 cost 0.035363
epoch   50/1000 cost 0.035018
epoch   60/1000 cost 0.034680
epoch   70/1000 cost 0.034348
epoch   80/1000 cost 0.034022
epoch   90/1000 cost 0.033703
epoch  100/1000 cost 0.033389
epoch  110/1000 cost 0.033081
epoch  120/1000 cost 0.032778
epoch  130/1000 cost 0.032481
epoch  140/1000 cost 0.032189
epoch  150/1000 cost 0.031902
epoch  160/1000 cost 0.031620
epoch  170/1000 cost 0.031343
epoch  180/1000 cost 0.031071
epoch  190/1000 cost 0.030804
epoch  200/1000 cost 0.030541
epoch  210/1000 cost 0.030282
epoch  220/1000 cost 0.030028
epoch  230/1000 cost 0.029777
epoch  240/1000 cost 0.029531
epoch  250/1000 cost 0.029289
epoch  260/1000 cost 0.029051
epoch  270/1000 cost 0.028816
epoch  280/1000 cost 0.028586
epoch  290/1000 cost 0.028358
epoch  300/1000 cost 0.028135
epoch  310/1000 cost 0.027915
epoch  320/1000 cost 0.027698
epoch  330

In [16]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

In [17]:
torch.manual_seed(1)

In [18]:
model = nn.Linear(4,3)

In [22]:
optimizer = optim.SGD(model.parameters(), lr=0.1)

nb_epochs = 1000
for epoch in range(nb_epochs+1):
    hypo = model(x_train)
    cost = F.cross_entropy(hypo, y_train)
    
    optimizer.zero_grad()
    cost.backward()
    optimizer.step()
    
    if epoch % 20 ==0:
        print('epoch {:4d}/{} cost {:4f}'.format(epoch, nb_epochs, cost.item()))

epoch    0/1000 cost 1.616785
epoch   20/1000 cost 0.904600
epoch   40/1000 cost 0.778017
epoch   60/1000 cost 0.722806
epoch   80/1000 cost 0.686341
epoch  100/1000 cost 0.658891
epoch  120/1000 cost 0.636713
epoch  140/1000 cost 0.617946
epoch  160/1000 cost 0.601539
epoch  180/1000 cost 0.586845
epoch  200/1000 cost 0.573443
epoch  220/1000 cost 0.561047
epoch  240/1000 cost 0.549451
epoch  260/1000 cost 0.538507
epoch  280/1000 cost 0.528102
epoch  300/1000 cost 0.518151
epoch  320/1000 cost 0.508588
epoch  340/1000 cost 0.499357
epoch  360/1000 cost 0.490416
epoch  380/1000 cost 0.481729
epoch  400/1000 cost 0.473265
epoch  420/1000 cost 0.465000
epoch  440/1000 cost 0.456911
epoch  460/1000 cost 0.448979
epoch  480/1000 cost 0.441185
epoch  500/1000 cost 0.433516
epoch  520/1000 cost 0.425956
epoch  540/1000 cost 0.418493
epoch  560/1000 cost 0.411114
epoch  580/1000 cost 0.403807
epoch  600/1000 cost 0.396563
epoch  620/1000 cost 0.389370
epoch  640/1000 cost 0.382218
epoch  660

In [23]:
class Softmax(nn.Module):
    def __init__(self):
        super().__init__()
        self.linear = nn.Linear(4,3)
        
    def forward(self,x):
        return self.linear(x)

In [24]:
model = Softmax()

In [25]:
optimizer = optim.SGD(model.parameters(),lr=0.1)

In [26]:
for epoch in range(nb_epochs+1):
    hypo = model(x_train)
    cost = F.cross_entropy(hypo, y_train)
    
    optimizer.zero_grad()
    cost.backward()
    optimizer.step()
    
    if epoch % 20 == 0 :
        print('epoch {:4d}/{} cost {:4f}'.format(epoch, nb_epochs, cost.item()))

epoch    0/1000 cost 2.637636
epoch   20/1000 cost 0.887444
epoch   40/1000 cost 0.773795
epoch   60/1000 cost 0.714015
epoch   80/1000 cost 0.675676
epoch  100/1000 cost 0.647903
epoch  120/1000 cost 0.625999
epoch  140/1000 cost 0.607701
epoch  160/1000 cost 0.591800
epoch  180/1000 cost 0.577594
epoch  200/1000 cost 0.564643
epoch  220/1000 cost 0.552655
epoch  240/1000 cost 0.541428
epoch  260/1000 cost 0.530818
epoch  280/1000 cost 0.520717
epoch  300/1000 cost 0.511043
epoch  320/1000 cost 0.501733
epoch  340/1000 cost 0.492736
epoch  360/1000 cost 0.484011
epoch  380/1000 cost 0.475525
epoch  400/1000 cost 0.467249
epoch  420/1000 cost 0.459159
epoch  440/1000 cost 0.451235
epoch  460/1000 cost 0.443458
epoch  480/1000 cost 0.435811
epoch  500/1000 cost 0.428281
epoch  520/1000 cost 0.420852
epoch  540/1000 cost 0.413514
epoch  560/1000 cost 0.406254
epoch  580/1000 cost 0.399061
epoch  600/1000 cost 0.391924
epoch  620/1000 cost 0.384833
epoch  640/1000 cost 0.377779
epoch  660